import Image from "next/image";
import Card from "src/components/Card";

export default function PhotoWidget() {
  return (
    <Card className="overflow-clip rounded-full p-0">
      <Image
        className="pointer-events-none"
        src="/me/me.jpg"
        alt="Chinmay Kunkikar"
        quality={75}
        placeholder="blur"
        blurDataURL="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAeAB4AAD/4QD4RXhpZgAASUkqAAgAAAADADEBAgAgAAAAMgAAADIBAgAU
        AAAAUgAAAGmHBAABAAAAZgAAAAAAAABBZG9iZSBMaWdodHJvb20gOC41LjIgKEFuZHJvaWQpADIw
        MjM6MDE6MTggMDE6MDQ6MzEACAAAkAcABAAAADAyMzEDkAIAFAAAAMwAAAAQkAIABwAAAOAAAAAR
        kAIABwAAAOgAAAAJkgMAAQAAAAAAAAABoAMAAQAAAAEAAAACoAkAAQAAABQAAAADoAkAAQAAABQA
        AAAAAAAAMjAyMzowMTowOCAwNzo0NzoxNQArMDU6MzAAACswNTozMAAA/9sAQwADAgIDAgIDAwMD
        BAMDBAUIBQUEBAUKBwcGCAwKDAwLCgsLDQ4SEA0OEQ4LCxAWEBETFBUVFQwPFxgWFBgSFBUU/9sA
        QwEDBAQFBAUJBQUJFA0LDRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU
        FBQUFBQUFBQU/8AAEQgAFAAUAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYH
        CAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHw
        JDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6
        g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk
        5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIB
        AgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEX
        GBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKT
        lJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX2
        9/j5+v/aAAwDAQACEQMRAD8A+HtE0JfDFhLeIlvqVsZAluluylWlcjYHY8oRlec4wO9fV/wL+GWt
        /ESdPDet+Hm0zVxp5v4JY5Ekt7iFXVGw4JAIMkfGcndnAxXE+NP2TZ/ht4NvtV8Q+MbPUovKEy+H
        9Hsbm4kuSq/u1kZQBGMDl2x93jJ4r3f9mLw5afDHTX8QaZYxeF31bRY0g1PxFbGGObymVXO0SKAM
        lPm6tjJPALa5LjcVl2JVSD1krPS916f5HBmWT4XMsFOOJ1cWra2af9d2cp4q/ZS1aw1ZoRYDhQTt
        kXHf2or07xj4j+JsWtuP7Q8NS5UHetlPg/8AkY0V90uJaL1klf0/4J8R/qslonP71/keVfsrfE7V
        5viFr/ia4S2utW01BFDJOrMpE0jbiRu6hY1UEYwuRzk16l+258QNbvNa8HIl5JZm80q5nZrSV4yj
        II3XGGwfmfo2eg98lFeNQS9vT9H/AOknt1ZP2dVX0938Zany9H8U/EMJeN7s3BUg+ZMWZiSAxyc+
        rGiiivLxdOHt5+6tzqwlSfsIe89j/9k="
        sizes="50vw"
        fill
      />
    </Card>
  );
}
